[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["python"]

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311", "gcc"]

[build.nixpacksPlan.phases.install]
cmds = ["pip install -r requirements.txt"]

[build.nixpacksPlan.phases.build]
cmds = []

[build.nixpacksPlan.start]
cmd = "python server.py"

[deploy]
startCommand = "python server.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
